version: "3.7"
services:
  php-fpm:
    build:
      context: ./
      dockerfile: _docker/php-fpm/Dockerfile
    container_name: php-fpm
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - local

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - ./storage/mongodb:/data/db
    networks:
      - local
    ports:
      - 27017:27017

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./_docker/nginx:/etc/nginx/conf.d
    networks:
      - local
    ports:
      - 8000:80
networks:
  local:
    driver: bridge
