version: "3.7"
services:
  php-fpm:
    build:
      context: ./
      dockerfile: _docker/php-fpm/Dockerfile
    container_name: php-fpm
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - local

  pgsql:
    image: postgres:latest
    container_name: pgsql
    restart: unless-stopped
    volumes:
      - ./storage/pgsql:/var/lib/postgresql/data
    networks:
      - local
    ports:
      - 5432:5432
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./_docker/nginx:/etc/nginx/conf.d
    networks:
      - local
    ports:
      - 8000:80
networks:
  local:
    driver: bridge
